language: node_js
node_js:
  - "12.13.0"
cache:
  directories:
    - frontend/node_modules
before_script:
  - cd frontend
script:
  - npm install
  - npm test
  - npm run lint
  - npm run build
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $github_token
#   local_dir: build
#   on:
#     branch: developer
