apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: tekton-hub
spec:
  template:
    spec:
      containers:
      - name: db-migration
        image: quay.io/sm43/db-e1225b1694ead6003d83a432fd4e95f5:latest
        env:
            - name: POSTGRESQL_HOST
              value: db
            - name: POSTGRESQL_PORT
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRESQL_PORT
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRESQL_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRESQL_PASSWORD
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api
                  key: GITHUB_TOKEN
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api
                  key: CLIENT_SECRET
      restartPolicy: Never
  backoffLimit: 3
